title: "Gaza's \"Batrachomyomachia\""
description: "Theodorus of Gaza's Attic prose paraphrase of the \"Batrachomyomachia\""
plugins:
  - jekyll-remote-theme
  - jekyll-github-metadata
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
remote_theme: ryanfb/jekyll-theme-palaios
author:
  name: Ryan Baumann
  first_name: Ryan
  last_name: Baumann
  email: ryan.baumann@gmail.com
  twitter: ryanfb
  url: https://ryanfb.github.io/
